config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users

  get 'home/about'
  get 'posts/myposts'

  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, length: {minimum:1, maximum:100}
    validates :description, presence: true, length: {minimum:1, maximum:500}
    validates :keywords, presence: true, length: {minimum:1, maximum:100}

    has_many_attached :images
    
    belongs_to :user

    before_create :randomize_id
    private
    def randomize_id
        begin
            self.id = SecureRandom.random_number(1_000_000_000)
        end while User.where(id: self.id).exists?
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

        has_many :posts

        before_create :randomize_id
        private
        def randomize_id
          begin
            self.id = SecureRandom.random_number(1_000_000_000)
          end while User.where(id: self.id).exists?
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, expect: [:index, :show]  
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  def myposts
    @posts = Post.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :keywords, :user_id, images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/about.html.erb
<h2> Welcome to our Instagram Clone using Ruby on Rails.</h2>
<h2> This is the page with Static Content</h2>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small blue pt-4">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase">Footer Content</h5>
        <p>Here you can use rows and columns to organize your footer content.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Home", root_path, class:"navbar-brand", style:"margin-left: 20px;"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent" style="margin-left: 20px;">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        
      </li>
      <li class="nav-item">
        <%= link_to "Upload Post", new_post_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "About Page", home_about_path, class:"nav-link"%>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Sign out", destroy_user_session_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Edit Account", edit_user_registration_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "View my Posts", posts_myposts_path, class:"nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class:"sign-up nav-link" %>
      </li>
      <% end %>

    </ul>
  
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <%= yield %>
    <%= render "layouts/footer"%>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="col-xl-4 col-md-6 col-sm-8 col-10" 
style="margin: auto;">
<%= form_with(model: post) do |form| %>
  <h1>New post</h1>

  <div>
    <% invalid = post.errors.include?(:title)%>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: "form-control" %>
    <% if invalid%>
      <p style="color: red"><%= post.errors.full_messages_for(:title).join(" ,") %></p>
    <% end %>
  </div>

  <div>
    <%= form.text_field :user_id, type: "hidden", value: current_user.id %>
  </div>

  <div>
    <% invalid = post.errors.include?(:description)%>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class: "form-control" %>
    <% if invalid%>
      <p style="color: red"><%= post.errors.full_messages_for(:description).join(" ,") %></p>
    <% end %>
  </div>

  <div>
    <% invalid = post.errors.include?(:keywords)%>
    <%= form.label :keywords, style: "display: block" %>
    <%= form.text_field :keywords, class: "form-control" %>
    <% if invalid%>
      <p style="color: red"><%= post.errors.full_messages_for(:keywords).join(" ,") %></p>
    <% end %>
    <%= form.file_field :images, multiple: true%>
  </div>

  <div>
    <%= form.submit class:"btn btn-dark col-12"%>
  </div>
<% end %>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="post-container">
  <p>
    <%# <strong>Title:</strong> %>
    <%= post.title %>
  </p>

  <p>
    <%# <strong>Description:</strong> %>
    <%= post.description %>
  </p>

  <p>
    <%# <strong>Keywords:</strong> %>
    <%= post.keywords %>
  </p>
  <p>
      <%= link_to "", post, class:"post-link" %>
  </p>
  <% post.images.each do |image| %>
    <%= image_tag(image, style: "object-fit: cover; 
    <%# width: 200px; height: 600px;")%>
  <% end  %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag("post")%>
<p style="color: green"><%= notice %></p>
<div id="posts" class="text-center">
  <% @posts.each do |post| %>
    <%= render post %>
    
  <% end %>
</div>

app/views/posts/myposts.html.erb
<%= stylesheet_link_tag("post")%>
<p style="color: green"><%= notice %></p>
<div id="posts" class="text-center">
  <% @posts.each do |post| %>
    <%= render post %>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="row"><%= render "form", post: @post %>
</div>
<br>

<%# <div>
  <%= link_to "Back to posts", posts_path %>
<%# </div> %> 

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>